import streamlit as st
import time 
st.title("Become Acquainted")
st.text("")
time.sleep(1)
st.subheader("Hey there stupid stranger...")
time.sleep(2)
st.subheader("Let's Know each other in this shit world")
time.sleep(2)
st.subheader("U begin!!!")
time.sleep(1)
st.subheader("Tell me about Yourself-")
st.text_area("")
b = st.button("respond")
if(b==1):
    st.subheader("Good  to  know  about  U  BITCH")
    time.sleep(3)
    st.subheader("I am   Mr . Chintu")
    time.sleep(3)
    st.subheader("I  am  a  PHP  Programmer  without  knowing  PHP")
    time.sleep(3)
    st.subheader("I made an app for which 3 CEO fighted for...")
    time.sleep(3)
    st.subheader("I like to watch naughty-naughty videos and play with PP.")
    time.sleep(3)
    st.subheader("ENOUGH..")
    time.sleep(3)
    st.subheader("Now U know me and I know you")
    time.sleep(3)
    st.subheader("So...FUCK OFF!!!!")
    time.sleep(10)
    st.subheader("U still here??...")
    time.sleep(1)
    st.subheader("Wat an ASSHOLE...")
    st.subheader("Just go bitch I don't feel like talking to u anymore")
    st.subheader("Cauz I am talking with my PP :P")